# Generated by Django 4.2.2 on 2023-07-06 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=150, verbose_name='заголовок')),
                ('slug', models.CharField(max_length=180, verbose_name='слаг')),
                ('content', models.TextField(verbose_name='контент')),
                ('image_preview', models.ImageField(blank=True, null=True, upload_to='blog_image_preview/')),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата создания')),
                ('is_publish', models.BooleanField(default=True, verbose_name='дата создания')),
                ('views_count', models.BigIntegerField(default=0, verbose_name='Количество просмотров')),
            ],
            options={
                'verbose_name': 'запись блога',
                'verbose_name_plural': 'записи блога',
                'ordering': ('creation_date',),
            },
        ),
    ]
