# Generated by Django 4.2.2 on 2023-07-07 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogentry',
            name='slug',
            field=models.CharField(blank=True, max_length=180, null=True, verbose_name='слаг'),
        ),
    ]
