# Generated by Django 4.2.2 on 2023-07-20 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogentry_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogentry',
            old_name='is_publish',
            new_name='is_published',
        ),
    ]
