# Generated by Django 4.2.2 on 2023-07-20 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_is_publish_blogentry_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogentry',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
    ]
