# Generated by Django 4.2.2 on 2023-06-21 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='имя')),
                ('description', models.TextField(verbose_name='описание')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='имя')),
                ('description', models.TextField(verbose_name='описание')),
                ('image_preview', models.ImageField(upload_to='image_preview/')),
                ('category', models.BigIntegerField(verbose_name='id категории')),
                ('price', models.IntegerField(verbose_name='цена')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('update_date', models.DateField(verbose_name='дата изменения')),
            ],
            options={
                'verbose_name': 'имя',
                'verbose_name_plural': 'продукты',
                'ordering': ('price',),
            },
        ),
    ]
