# Generated by Django 4.2.2 on 2023-06-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_preview',
            field=models.ImageField(blank=True, null=True, upload_to='image_preview/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='update_date',
            field=models.DateField(auto_now=True, verbose_name='дата изменения'),
        ),
    ]
