# Generated by Django 4.2.2 on 2023-07-16 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_product_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('price',), 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
    ]
